services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=*
      - DB_PORT=*
      - DB_NAME=*
      - DB_USER=*
      - DB_PASSWORD=*
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      start_period: 30s
      retries: 3
    restart: unless-stopped