services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=109.71.245.217
      - DB_PORT=5432
      - DB_NAME=BSApp
      - DB_USER=postgres
      - DB_PASSWORD=183492awedxzs
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 15s
      timeout: 5s
      start_period: 30s
      retries: 3
    restart: unless-stopped